name: Canary Builds

on:
  push:
    branches:
    - master

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  ContinuousIntegrationBuild: true
  BuildType: canary

jobs:
  build:
    name: Build & Test
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1

    - name: Setup Dotnet for use with actions
      uses: actions/setup-dotnet@v1

    - name: Test
      run: dotnet test -c Release -p:EnableCoverage=true

    - name: Upload Code Coverage
      uses: codecov/codecov-action@v2
      with:
        files: out/coverage/**/*.opencover.xml
      if: ${{ always() }}

    - name: Upload TestResults
      uses: actions/upload-artifact@v2
      with:
        name: TestResults & Coverage
        path: |
          out/coverage/
          out/testresults/*.trx
      if: ${{ always() }}

    - name: Pack
      run: dotnet pack -c Release

    - name: Upload Packages
      uses: actions/upload-artifact@v2
      with:
        name: packages
        path: out/packages/*.nupkg

  deploy-to-gpr:
    name: Deploy to GPR
    needs: [ build ]
    runs-on: ubuntu-latest
    environment: GPR
    env:
      GPR_REPOURI: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
    steps:
    - uses: actions/checkout@v1

    - uses: actions/download-artifact@v2
      name: Download Packages from build job
      with:
        name: packages
        path: out/packages/

    - name: Setup Dotnet for use with actions
      uses: actions/setup-dotnet@v1

    - name: Publish CI Package to GitHub Package Registry
      run: |
        dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name GPR "${{env.GPR_REPOURI}}"
        dotnet nuget push "*.nupkg" --source GPR
      working-directory: out/packages/
