name: Canary Builds

on:
  push:
    branches:
    - master

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  run-build-and-test:
    uses: ./.github/workflows/BuildAndTest.yml@master
    with:
      buildtype: canary
  deploy-to-gpr:
    runs-on: ubuntu-latest
    needs: [run-build-and-test]
    # env:
    #   GPR_REPOURI: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
    steps:
    # - name: Setup Dotnet for use with actions
    #   uses: actions/setup-dotnet@v1
    - name: Download packages from build
      uses: actions/download-artifact@v2
      with:
        name: packages
        path: packages-out/
    - name: Display structure of downloaded files
      run: ls -R
    # - name: Publish CI Package to GitHub Package Registry
    #   run: |
    #     dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name GPR "${{env.GPR_REPOURI}}"
    #     dotnet nuget push "${{env.PackageOutputPath}}\*.nupkg" --source GPR
