name: CI
on: [push]
jobs:
  build:
    runs-on: [windows-2019]
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      BuildType: canary
      Configuration: Release
    steps:
    - uses: actions/checkout@v1
      
    - name: Setup Dotnet for use with actions
      uses: actions/setup-dotnet@v1.0.0
      with:
        version: 2.2.301

    - name: Test
      run: dotnet test -p:EnableCoverage=true --logger:"console;verbosity=normal"

    - name: Pack
      run: dotnet pack -p:PackageOutputPath="$env:GITHUB_WORKSPACE/out/packages"
    
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Packages
        path: out/packages