name: CI

on:
  pull_request:
  push:
    branches:
    - master

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  PackageOutputPath: ${{ github.workspace }}/out/packages
  GPR_REPOURI: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Dotnet for use with actions
      uses: actions/setup-dotnet@v1
    - name: Test
      run: dotnet test -c Release -p:EnableCoverage=true -p:ContinuousIntegrationBuild=true -p:BuildType=canary
    - name: Pack
      run: dotnet pack -c Release -p:ContinuousIntegrationBuild=true -p:BuildType=canary
    - name: Upload Code Coverage
      uses: codecov/codecov-action@v2
      with:
        files: tests/**/*.opencover.xml
        verbose: true
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Packages
        path: out/packages
    - name: Publish CI Package to GitHub Package Registry
      if: ${{ github.ref == 'refs/heads/master' }}
      run: |
        dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name GPR "${{env.GPR_REPOURI}}"
        dotnet nuget push "${{env.PackageOutputPath}}/*.nupkg" --source GPR
