name: PR Builds

on:
  pull_request:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  ContinuousIntegrationBuild: true
  BuildType: dev

jobs:
  build:
    name: Build & Test
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1

    - name: Setup Dotnet for use with actions
      uses: actions/setup-dotnet@v1

    - name: Test
      run: dotnet test -c Release -p:EnableCoverage=true

    - name: Upload Code Coverage
      uses: codecov/codecov-action@v2
      with:
        files: out/coverage/**/*.opencover.xml
      if: ${{ always() }}

    - name: Upload TestResults
      uses: actions/upload-artifact@v2
      with:
        name: TestResults & Coverage
        path: |
          out/coverage/
          out/testresults/*.trx
      if: ${{ always() }}

    - name: Pack
      run: dotnet pack -c Release

    - name: Upload Packages
      uses: actions/upload-artifact@v2
      with:
        name: packages
        path: out/packages/*.nupkg
